### PR TITLE
#270 Fix member user field nullable

### LINKED ISSUE #270: Make user ID field in Member non-nullable
Currently, the Member to User ID field is allowed to be NULL. A NULL entry can result in malfunction (password reset, ...). Shouldn't we enforce the OneToOne link with non-nullable?

### PR DESCRIPTION
**Pull request by nixnuex**
Please add following data migration before schema migration to trigger `pre_save` user creation in case there are instances with user `NULL` in the field:

    for m in Member.objects.all():
        if getattr(m, 'user', None) is None:
            m.save()

Fixes #270

### CODE REVIEW

**Comment by nixnuex** [comment]
Travis is hanging at the makemigrations step default value because I did not include the migration as requested.

**Comment by motu55** [comment]
the corresponding migrations 28 and 29 are now in the branch so you can adapt them

**Comment by motu55** [comment]
target branch of this pullrequest is release_1.4 also fill your migrations in the corresponding 1_4 migrations

**Comment by nixnuex** [comment]
> target branch of this pullrequest is release_1.4 also fill your migrations in the corresponding 1_4 migrations

Done. See b448dc0

**Pull request merged**
