### PR TITLE
#290 Implement enhanced sorting in admin through django-admin-sortable2

### PR DESCRIPTION
**Pull request by nixnuex**
Idea from #286: include order for Product, ProductSize, ProductType easily manageable through `django-admin-sortable2`.

Note: This requires either a data migration to set the `sort_order`s to unique initial values for existing objects or to run the commands:

    python manage.py reorder juntagrico.SubscriptionSize
    python manage.py reorder juntagrico.SubscriptionType
    python manage.py reorder juntagrico.SubscriptionProduct

### CODE REVIEW

**Comment by motu55** [comment]
please create in issue for this for trackeability

**Comment by nixnuex** [comment]
Created issue #290

**Comment by motu55** [comment]
target branch of this pullrequest is release_1.4 also fill your migrations in the corresponding 1_4 migrations

**Comment by nixnuex** [comment]
> target branch of this pullrequest is release_1.4 also fill your migrations in the corresponding 1_4 migrations

Done. See 4664096e9a38c0d4419ae85d86c8dfa244fb19d9

**Important**: This requires all instances to include:

    INSTALLED_APPS = (
        ...
        'adminsortable2',
        ...
    )

This should be reflected in documentation and release notes.

**Pull request merged**
