### PR TITLE
Rework of depot list layout / generation

### LINKED ISSUE #240: Depot list: subscription type and size text overlapping
In the depot list, the subscription type and size often are too wide for the table column width and thus overlap with the neighboring text. This makes it hard to read the header of the table.

Maybe rotating the text by 90° would solve the issue?

DepotListIssue

### PR DESCRIPTION
**Pull request by nixnuex**
This is work-in-progress to address some of the ongoing issues with the depot list:

- [x] Auto handling of page break by `xhtmltopdf` while repeating headers through `repeat="5"`
- [x] Move depot list messages to footer on every page
- [x] Prevent subscription types and sizes to overlap with neighboring cells (closes #240)
- [x] Optimize space usage for eco printing
- [x] ~~Remove separation sub/etra-sub from depot list html template and handle in DAO~~

### CODE REVIEW

**Comment by motu55** [comment]
fot the size overlapping
we are usuing a monospace font so basically the width can be defines using the unit em
what is the las point about?

**Comment by nixnuex** [comment]
The point "Remove separation sub/etra-sub from depot list html template and handle in DAO" refers to the quite complex structure of the current depot list template. There is a lot of different input data structures and logic in there. I would propose to clean the logic and make the depot list template more maintainable by putting the data logic / data table assembly into a DAO. In there, all the sorting and combination of possible main & extra subscriptions will happen and the template will just loop through.

What do you think?

**Comment by motu55** [comment]
the current way was initiated by @pascalfree so i think his input here needs also to be considered
we had such a way where we calculated all of it and looped through it
this was less performant and also the template filters we have now allow for a more flexible way to reuse the code and create new forms of lists

**Comment by nixnuex** [comment]
Will focus on the layout issues first and not touch the logic unless desired.

**Comment by nixnuex** [comment]
I cleaned up the styles and optimized the column width to make more room for products and sizes. Unfortunately, I did not find a workaround to really solve the issue. Did not touch the data logic.

Please check and try out this new design with main change auto table break handling by xhtml2pdf and optimized style/spacing.

New Depot List

**Comment by motu55** [comment]
have you tried to define the width something like this
`<td style="width: {{ size.name|length }}`em;">{{ size.name }}</td>

not sure if it would work and if my mock code is correct but i think rightly adapted it might work

**Comment by motu55** [comment]
ok i will merge this but keep the solution to calculate the width in my mind since we will come back to that solution some day

**Pull request merged**
