### PR TITLE
Better Jobs

### PR DESCRIPTION
**Pull request by pascalfree**
#49

New Features:
- [x] Calendar view
- [x] Navigation to past and future jobs
- [x] Display taken vs. total slots
- [x] Search entire job description
- [x] Responsive

Todo:
- [ ] Job extras
- [ ] Adapt background color in calender view to highlight jobs that need people
- [ ] Theme fine tuning
- [ ] outsource to extension

TBD:
- [ ] Replace front page table?
- [ ] Combine css and js of fullcalendar?
- [ ] Core jobs are bold now. Keep it?
- [ ] Including bootstrap.bundle for tooltips. Include Popper.js separately instead?

### CODE REVIEW

**Comment by motu55** [comment]
- searching for weekday and area does not work
- search only work in current page
- past jobs by pagination
- what about job extras?
- list calendar toggling not possible in mobile mode
- list was responsive before ;)
- past jobs where accesible before and morea easiliby found through date format
- past jobs do not work 

there is a lot to do here before we get the same functionality as before

the goal is to get members quickly into jobs therefore they have to quickly find their job.
this might in some cases require a calendar view but according to the ux study it is not the primary source
a calendar view might make sens to get an overview where peaople are missing for jobs, for that the jobs in the calendar view would have to have different background colors to see where peopla are missing.

still think this should go into an extension and we keep the normal simple list for now, only thing at some point we should replace is the image showing the status with the numbers

**Comment by pascalfree** [comment]
>     * searching for weekday and area does not work
Works for me
>     * search only work in current page
This is Intentional. Date radius can be expanded up to 90 days which should be enough for normal use cases. One year can be searched within 5 clicks. Date radius is clearly stated on the top.
>     * past jobs by pagination
Yes. 
>     * what about job extras?
Todo
>     * list calendar toggling not possible in mobile mode
Can be added, but calendar view is too wide for mobile
>     * list was responsive before ;)
Not enough
>     * past jobs where accesible before and morea easiliby found through date format
date format can still be filtered with regex
>     * past jobs do not work
work for me

> still think this should go into an extension

can do

**Comment by motu55** [comment]
grafik
grafik

**Comment by motu55** [comment]
some how past jobs now work on my machine too

>     * past jobs where accesible before and morea easiliby found through date format
> date format can still be filtered with regex

unfortunatelly only a few are able to write regex

>    * list was responsive before ;)
>Not enough

please elaborate

**Comment by pascalfree** [comment]
Moved it to an extension (yet unofficial): https://github.com/mehalsgmues/juntagrico_calendar
Can be closed here.

**Pull request closed without merging**
