### PR TITLE
auto complete fields in the admin

### PR DESCRIPTION
**Pull request by motu55**
I don't know why I never thought of these.
Will also help with the problem of scrolling through too long drop downs because usally you know exactly which entry you want and are not browsing for a suitable item

### CODE REVIEW

**Comment by pascalfree** [comment]
Nice.
Let's use it consistently everywhere: `Delivery.subscription_size` and `BillingPeriod.type` I found are still using the normal select.

**Comment by motu55** [comment]
@pascalfree added the missing fields

**Review by pascalfree — COMMENTED** [review]
It seems the auto complete field does not use the querysets that we override with `formfield_for_foreignkey` but the one from `get_queryset` of the related model. Which is fine in our case.
But in this case we can remove most `formfield_for_foreignkey` methods. right?
Also the `visible` flag on the JobType is obsolete. But let's keep this for now.

**Comment by motu55** [comment]
i checked the this assumption and i see that the formfield_for_foreignkey is still called with the corresponding field names
so i am not shure if these are obsolete but as far as i think to know the queryset returned from formfield_for_foreignkey is used during validation that now invalid value can be set. so this method still fullfills a purpose

**Review by pascalfree — APPROVED** [review]

**Pull request merged**
