### PR TITLE
member: New assignment status widget

### LINKED ISSUE #564: Clearer assignment overview in menu
The assignment overview in the menu might be misleading in at least 2 ways:

* If all assignments are done (some by another member in the subscription) the semi-transparent symbol gives the impression that these are missing
* If core assignments are required, the overview does not indicate that.

### PR DESCRIPTION
**Pull request by pascalfree**
resolves #564

The widget can be included with or without counting future jobs:

```
{% load juntagrico.widgets %}
{% assignments request.user.member %}
{% assignments request.user.member future=False %}
{% assignments request.user.member future=True %}
```

Which would output like this:
Bildschirmfoto vom 2023-02-04 14-37-46
first is the current display for comparison. If future is not set, it will count all assignments, if future is True, the future assignments will be displayed differently.
Note that the core assignment bar will only show if core assignments are required for this specific member.

# Todo

- [x] Make it easy to switch to the new widget, for early adopters. Or make it easy to revert to the old one.
- [x] Display a summary below the bars to make them more accessible. e.g.: "2 assignments left, of which 1 must be core".
- [x] Fine tune texts.

# Future

- [ ] Dedicate a page to the assignments of a sub with explanations and all #586 #487

### CODE REVIEW

**Comment by motu55** [comment]
If i understand it correctly you want to replace thesingle assingments with progress bars?
I know at least one organisation which will be furious when the böhnli are no longer böhnli ;)

Also from a ux study it shows that to many informations are packed in our current graph and a progressbar does not nescessary help. some part of the problem is that people don't understand the concept of core assignments.

I would propose a textual representation rather than a progress bar. something like

"In your subscription you have 5 böhnli out of 10 required (1 Core out of 3 required). A more detailed overview can be found here", where here redirects to the subscription overview page (or an assignment overview page if the subscription overview page gets to crwoded) where all the ssignments are diplayed and who did them to get an easy overview whod did how many assignments. this might also be beneficial for larger groups who chare a subscription who want to know who has not made enough assignments, also there could be a link or snippet which explains what core assignments are

**Comment by motu55** [comment]
for the embedding of the new wifgets or widgets in general i would suggest a jump template which contains all the widgets and is included in the menu template, this way cooperations only have to overwrite the jump template
this would also allow for a vide variety of assignments widgets like texutal or graphical and the organisations can easily chose which to use

**Comment by motu55** [comment]
I just saw while testing that people with no subscription but still doing assingments do not see them what is a bit sad, maybe we should find a solution for that as well

**Comment by pascalfree** [comment]
Customizability and an option to keep the old one is for sure planned.
A block should be enough to make it overridable. I'll test the possibilities.

**Pull request merged**
