### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by siancu**
I updated some of the dependencies of juntagrico:
- icalendar
- reportlab
- schwifty
- xhtml2pdf
- XlsxWriter

I ran the app and all the tests and it all seems fine.

I didn't update django itself nor any other of the django libraries we use. Should I?

### CODE REVIEW

**Comment by pascalfree** [comment]
Thanks.
To your question: Yes please upgrade django as well.

**Comment by pascalfree** [comment]
We stay at django 4.0 for the juntagrico 1.6 release due to #641. As django 4.0 is compatible up to python 3.10, I removed the test on python 3.11.
I upgraded the other packages (no major releases).

**Comment by pascalfree** [comment]
Updated external static files:
- bootstrap to 4.6.2
- datatables to 1.13.7
- fontawesome to 6.4.2: Upgrade instruction: Needs to be added to installed apps
- leaflet to 1.9.4
- jquery to 3.7.1
- tinymce 5.10.8

Also fixed language support for tinymce and added all languages that juntagrico supports.

TODO
- [ ] `ionicons` and `mid shall be deprecated with instructions how to add them manually if needed.
- [ ] Replace `datepicker` by HTML5 `type="date"` input field, which is well supported by now.
- [ ] Check `attachment_appender.js`, `bootstrap-input-spinner.js` and `require.min.js`

**Comment by pascalfree** [comment]
I managed to upgrade to django 4.2 in #641. 

- [ ] add python 3.11 to test action again. after merging #641

**Comment by pascalfree** [comment]
# Upgrade instructions

The icon sets except for fontawesome have been removed. they can be reinstalled if needed using the [STYLES](https://juntagrico.readthedocs.io/en/latest/settings.html#styles) setting.

**Comment by siancu** [comment]
@pascalfree I had a look at your latest changes and they look good to me. Maybe you can merge the branch now into release_1.6?

**Pull request merged**
