### PR TITLE
269 Add share creation date

### LINKED ISSUE #269: Add share field creation date
Currently there is no information on when a member requested more shares. I would propose to add a field `creation_date` which defaults to date of creation to make share management more traceable.

### PR DESCRIPTION
**Pull request by nixnuex**
Close #269 

Please add migration as follows, to preserve old share entries with empty creation date and only generate new shares with current date:

    from django.db import migrations, models
    import django.utils.timezone

    class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0027_auto_20200921_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Erzeugt am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Erzeugt am'),
        ),
    ]

### CODE REVIEW

**Review by motu55 — CHANGES_REQUESTED** [review]
the field should be read only in the admin
also use the commit message format "#issuenr some text"

**Review by motu55 — APPROVED** [review]
will be merged once we merge all the pull request with migrations

**Comment by motu55** [comment]
the corresponding migrations 0028 and 0029 can now be adapted

**Comment by nixnuex** [comment]
> the corresponding migrations 0028 and 0029 can now be adapted

Done.

**Pull request merged**
