### PR TITLE
Support for depot pickup times

### PR DESCRIPTION
**Pull request by pascalfree**
# TODO
- ~Rename "weekday" field to "delivery day"~ delivery day is obsolete with #589
- ~Add field to override pick-up date (defaults to delivery day)~ obsolete #589
- [x] Show in depotlist
- [x] Show during depot selection in signup process
- [x] Release notes

# Release Notes
# Member Features
- Optionally display pickup time and duration for each depot.

### CODE REVIEW

**Comment by motu55** [comment]
What about a depot where for example the pickupt time is monday 10-12, tuesday 10-11 and wendesday-14-19 and after that the vegetables are eaten by someone else?
either we jack this up to 11 or we just leave it in the description as it is for now

**Comment by pascalfree** [comment]
More complex cases can go into the description (as they do now)
The current weekday field is insufficient if there are multiple days to pick up things. e.g. Friday 17:00 to Saturday 17:00
This PR covers the most common use cases.

**Comment by motu55** [comment]
the weekday field does at the moment not really model the pickup time. it models the day the vegetables are delivered and is basically used to group the depots on the depot list. for that purpose it is sufficient. 
So what you want to display is the the 24 hour rule until the vegetables have to be collected for wich the the name pick up times in my opinion is a bit misleading since it does more sound like opening times of a depot which is not allways accessible and not like until when the vegetables have to be collected.

**Comment by pascalfree** [comment]
Members see the weekday and expect that this is the day they can pick it up. If it isn't intended for that, it shouldn't be displayed at all to the members. But i think everybody uses it exactly for that: the day of delivery = pickup day.
I think pickup_time sounds exactly like the time you can pick up stuff. How would you name it then?

If there is no deadline to pick up, the pickup_duration can be left empty and it will just show as e.g. "Tuesday 14:00" or to keep it unchanged, just leave both fields empty and it displays, as before, just the day.
I don't think this is very controversial.

**Pull request merged**
